### ISSUE TITLE
Merge changes of Joshua

### ISSUE THREAD

**Issue by sebtno** [sebtno/FIR#1] opened 2018-01-30 06:16 UTC
This issue to be assigned to Joshua.
Specifically the dropdown lists for Categories and Confidence-Values
MVC parts have changes. Pull latest, then merge with care.

**Comment by JSeam2** [comment] 2018-02-04 15:02
Merged the changes. The issue is now fixed.

**Closed by JSeam2** 2018-02-04 15:02 UTC
